project:
  type: website

website:
  title: "informatique"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Python
        menu:
          - href: doc/python_format_texte.qmd
            text: "Format Texte"

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    css: styles.css